notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=nginx

before_install:
  - docker pull alpine

script:
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" .
  - docker run -d --rm --name nginx demyx/"$DEMYX_REPOSITORY"
  - docker exec -t nginx nginx -V

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - bash travis.sh
